package com.java.exception;

public class ExceptionDemo {
	public static void main(String[] args) {
		int a=10;
		int b=0;
		int c=a/b;
		System.out.println("main completes");
		

		/*int a=10;
		int b=0;
		try {
			int c=a/b;
		}
		catch(ArithmeticException e) {
			System.out.println("Exception caught");
		}
		System.out.println("main completes");*/
		
		/*int a=10;
		int b=0;
		try {
			int c=a/b;
		}
		finally {
			System.out.println("take an action on exception");
		}*/

	}

}
